### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by CaseyTal** [joseangelmt/AutoInsertPin#2]
Hello! I'd really like to set this up for a Windows installation with basic smart cards that the user could insert and get logged in immediately. However, I'm not finding any documentation on how to actually set this up. 

Please help. Thanks!

**Comment by joseangelmt** [comment]
Hello,

Sorry for the delay in replying, I had not seen this message.
You just have to run the program passing as parameter the password of your YubiKey (or device you have).

The program will stay in standby (it is not a service, it is a console program, so you cannot close the console) waiting for Windows to request the key password. 

As soon as the program detects that Windows is displaying the dialog box, it will automatically move the cursor to the 
edit control, enter the password and click.

The program is set to detect the dialog box in English. If your computer is in another language, you will have to change the text "Windows Security" to the equivalent in your language.
in your language.
